// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lmd.ggzy.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect GgzyBusinessTypeWay_Roo_Jpa_Entity {
    
    declare @type: GgzyBusinessTypeWay: @Entity;
    
    declare @type: GgzyBusinessTypeWay: @Table(name = "GGZY_BUSINESS_TYPE_WAY");
    
   
    
}
