// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lmd.ggzy.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect GgzyEvaluationReport_Roo_Jpa_Entity {
    
    declare @type: GgzyEvaluationReport: @Entity;
    
    declare @type: GgzyEvaluationReport: @Table(name = "GGZY_EVALUATION_REPORT");
    
}
