// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lmd.ggzy.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect GgzyBiddingCandidate_Roo_Jpa_Entity {
    
    declare @type: GgzyBiddingCandidate: @Entity;
    
    declare @type: GgzyBiddingCandidate: @Table(name = "GGZY_BIDDING_CANDIDATE");
    
}
