// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lmd.ggzy.domain;

import java.util.Collection;
import java.util.List;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;

privileged aspect GgzyProspectRecord_Roo_Json {
    
    public String GgzyProspectRecord.toJson() {
        return new JSONSerializer()
        .exclude("*.class", "*.handler","*.hibernateLazyInitializer").serialize(this);
    }
    
    public String GgzyProspectRecord.toJson(String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*").serialize(this);
    }
    
    public static GgzyProspectRecord GgzyProspectRecord.fromJsonToGgzyProspectRecord(String json) {
        return new JSONDeserializer<GgzyProspectRecord>()
        .use(null, GgzyProspectRecord.class).deserialize(json);
    }
    
    public static String GgzyProspectRecord.toJsonArray(Collection<GgzyProspectRecord> collection) {
        return new JSONSerializer()
        .exclude("*.class").serialize(collection);
    }
    
    public static String GgzyProspectRecord.toJsonArray(Collection<GgzyProspectRecord> collection, String[] fields) {
        return new JSONSerializer()
        .include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<GgzyProspectRecord> GgzyProspectRecord.fromJsonArrayToGgzyProspectRecords(String json) {
        return new JSONDeserializer<List<GgzyProspectRecord>>()
        .use("values", GgzyProspectRecord.class).deserialize(json);
    }
    
}
