// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package test.com.lmd.ggzy.domain;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import test.com.lmd.ggzy.domain.GgzyBasePro;

privileged aspect GgzyBasePro_Roo_ToString {
    
    public String GgzyBasePro.toString() {
        return new ReflectionToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE).setExcludeFieldNames("ggzyBidProes").toString();
    }
    
}
